proxies:

- name: [IFLIX]
  server: ikada.sing-box.space
  port: 443
  type: vless
  uuid: dee988c4-d6ae-4f45-9b2f-dea187bbc13e
  udp: true
  network: ws
  ws-opts: 
    path: /in-depth-analyze-to-ux-design/buy-vless-ws-pm-telegram-at-synricha
    headers: 
      Host: ikada.sing-box.space
  tls: true
  servername: vplay.iflix.com
  skip-cert-verify: true

- name: [IFLIX] NewMedia Express Pte Ltd
  server: free.mediafairy.site
  type: vmess
  port: 443
  uuid: f82d75b4-c952-4410-b6a3-314628c8ee1c
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: vplay.iflix.com
  network: ws
  ws-opts:
    path: /vmess-ws
    headers:
      Host: free.mediafairy.site
  udp: true
